name: .NET Framework build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  solution: 'RequestMocker.sln'
  configuration: 'Release'
  project_name: 'RequestMocker'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore ${{ env.solution }}

    - name: Build solution
      run: msbuild ${{ env.solution }} /p:Configuration=${{ env.configuration }} /p:Platform="Any CPU" /m /restore

    - name: Publish application
      run: msbuild ${{ env.solution }} /t:Publish /p:Configuration=${{ env.configuration }} /p:Platform="Any CPU"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: ./${{ env.project_name }}/bin/${{ env.configuration }}/${{ env.project_name }}.exe
