name: .NET Framework Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  Solution_Name: RequestMocker.sln
  Configuration: Release

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore dependencies with NuGet
      run: nuget restore $env:Solution_Name

    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration

    - name: Publish
      run: dotnet publish $env:Solution_Name --configuration $env:Configuration --no-build --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Executable
        path: ./publish/*
