name: Build and Publish

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet: ['3.1.x']
        include:
          - os: windows-latest
            rid: win-x64

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --no-restore --self-contained true --runtime ${{ matrix.rid }} --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.rid }}
        path: |
          **/publish/
