name: .NET Framework build

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

env:
  solution: RequestMocker.sln
  configuration: Release

jobs:
  build:
    runs-on: windows-latest
    env:
      SOLUTION_PATH: './${{ env.solution }}'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore ${{ env.SOLUTION_PATH }}

    - name: Build solution
      run: msbuild ${{ env.SOLUTION_PATH }} /p:Configuration=${{ env.configuration }} /p:Platform="Any CPU" /m /restore

    - name: Publish application
      run: msbuild ${{ env.SOLUTION_PATH }} /t:Publish /p:Configuration=${{ env.configuration }} /p:Platform="Any CPU" /p:PublishProfile=FolderProfile.pubxml

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: ./RequestMocker/bin/${{ env.configuration }}/publish/
